//
//  BakerShopData.swift
//  the baker house
//
//  Created by Trí Lai on 28/07/2023.
//

import Foundation
import CoreLocation

var bakerShops: [BakerShop] = [
    BakerShop(name: "Tous Les Jous",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry",  "Cake"],
              imageName: "TLJ_Logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Tiệm bánh MADI",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Cake"],
              imageName: "madi-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Paris Baguette",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry",  "Gourmet"],
              imageName: "paris-baguette-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),

    BakerShop(name: "Kinh Đô",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Moon cake"],
              imageName: "kinh-do-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Đức Phát",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Cupcake", "Cake"],
              imageName: "duc-phat-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Paris Gâteaux",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry",  "Gourmet"],
              imageName: "paris-gateaux-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Girval",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Cake"],
              imageName: "girval-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "ABC Bakery",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry",  "Cake", "Cupcake"],
              imageName: "abc-bakery-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Sweet Home Bakery",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Cake", "Cupcake"],
              imageName: "sweet-home-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "BreadTalk",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Cake", "Cupcake"],
              imageName: "breadtalk-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Ryoyu",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Cake"],
              imageName: "ryoyu-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Hỷ Lâm Môn",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Moon cake", "Cake", "Cupcake"],
              imageName: "hy-lam-mon-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Satra Bakery & Café",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Gourmet"],
              imageName: "satra-bakery-cafe-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
    
    BakerShop(name: "Brodard Bakery",
              subheading: "Freshly Baked Everyday",
              description: "Since our launch into the United States in 2004, TOUS les JOURS [meaning \"everyday\" in French] has developed into a reputable neighborhood bakery specializing in French-Asian inspired baked goods, hand crafted beverages and bold, flavorful coffee and espresso made with the finest ingredients.We take pride in sourcing and using carefully selected ingredients and promises to bring freshness and quality to our customers. To date, we have more than 90 locations across the United States, and more than 1,650 worldwide.",
              address: "231 Đ. Hậu Giang, Phường 5, Quận 6, Thành phố Hồ Chí Minh 700000",
              rating: 4.5,
              category: ["Pastry", "Gourmet", "Cake", "Wedding"],
              imageName: "brodard-bakery-logo",
              location: CLLocationCoordinate2D(latitude: 10.749997,
                                               longitude: 106.666664)),
]
